markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Bruno Ghisi
url: http://brunoghisi.com
description: My personal blog
twitter: brunogh
github: brunogh
linkedin: http://www.linkedin.com/in/brunoghisi/en
gravatar_url: http://www.gravatar.com/avatar/410df0b7c43e35ed602efe281810b1ff